apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management
  labels:
    app: employee-management
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: employee-management
  template:
    metadata:
      labels:
        app: employee-management
    spec:
      containers:
        - name: employee-management
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
